'use strict';
var e,f="object"===typeof __ScalaJSEnv&&__ScalaJSEnv?__ScalaJSEnv:{},h="object"===typeof f.global&&f.global?f.global:"object"===typeof global&&global&&global.Object===Object?global:this;f.global=h;f.exportsNamespace=exports;h.Object.freeze(f);var aa={envInfo:f,semantics:{asInstanceOfs:2,arrayIndexOutOfBounds:2,moduleInit:2,strictFloats:!1,productionMode:!0},assumingES6:!1,linkerVersion:"0.6.22",globalThis:this};h.Object.freeze(aa);h.Object.freeze(aa.semantics);
var k=h.Math.imul||function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},ba=h.Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);return b+(a>>31)},ca=0,da=h.WeakMap?new h.WeakMap:null;function q(a){return function(b,c){return!(!b||!b.$classData||b.$classData.W!==c||b.$classData.U!==a)}}
function ea(a){for(var b in a)return b}function fa(a,b,c){var d=new a.za(b[c]);if(c<b.length-1){a=a.Z;c+=1;for(var g=d.Ka,l=0;l<g.length;l++)g[l]=fa(a,b,c)}return d}function ga(a){switch(typeof a){case "string":return r(ha);case "number":var b=a|0;return b===a?ia(b)?r(ja):ka(b)?r(la):r(ma):"number"===typeof a?r(na):r(oa);case "boolean":return r(pa);case "undefined":return r(qa);default:return null===a?a.Zd():ra(a)?r(sa):a&&a.$classData?r(a.$classData):null}}
function ta(a){switch(typeof a){case "string":return ua(t(),a);case "number":return va(wa(),a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||null===a?a.o():null===da?42:xa(a)}}function ya(a,b){var c=h.Object.getPrototypeOf,d=h.Object.getOwnPropertyDescriptor;for(a=c(a);null!==a;){var g=d(a,b);if(void 0!==g)return g;a=c(a)}}function za(a,b,c){a=ya(a,c);if(void 0!==a)return c=a.get,void 0!==c?c.call(b):a.value}
function Aa(a,b,c,d){a=ya(a,c);if(void 0!==a&&(a=a.set,void 0!==a)){a.call(b,d);return}throw new h.TypeError("super has no setter '"+c+"'.");}
var xa=null!==da?function(a){switch(typeof a){case "string":case "number":case "boolean":case "undefined":return ta(a);default:if(null===a)return 0;var b=da.get(a);void 0===b&&(ca=b=ca+1|0,da.set(a,b));return b}}:function(a){if(a&&a.$classData){var b=a.$idHashCode$0;if(void 0!==b)return b;if(h.Object.isSealed(a))return 42;ca=b=ca+1|0;return a.$idHashCode$0=b}return null===a?0:ta(a)};function ia(a){return"number"===typeof a&&a<<24>>24===a&&1/a!==1/-0}
function ka(a){return"number"===typeof a&&a<<16>>16===a&&1/a!==1/-0}function u(){this.pa=this.za=void 0;this.U=this.Z=this.s=null;this.W=0;this.Ma=null;this.la="";this.p=this.ja=this.ka=void 0;this.name="";this.isRawJSType=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function w(a,b,c){var d=new u;d.s={};d.Z=null;d.Ma=a;d.la=b;d.p=function(){return!1};d.name=c;d.isPrimitive=!0;d.isInstance=function(){return!1};return d}
function x(a,b,c,d,g,l,m){var p=new u,v=ea(a);l=l||function(a){return!!(a&&a.$classData&&a.$classData.s[v])};m=m||function(a,b){return!!(a&&a.$classData&&a.$classData.W===b&&a.$classData.U.s[v])};p.pa=g;p.s=c;p.la="L"+b+";";p.p=m;p.name=b;p.isInterface=!1;p.isRawJSType=!!d;p.isInstance=l;return p}
function Ba(a){function b(a){if("number"===typeof a){this.Ka=Array(a);for(var b=0;b<a;b++)this.Ka[b]=g}else this.Ka=a}var c=new u,d=a.Ma,g="longZero"==d?Ca().ia:d;b.prototype=new y;b.prototype.constructor=b;b.prototype.$classData=c;var d="["+a.la,l=a.U||a,m=a.W+1;c.za=b;c.pa=Da;c.s={b:1,Xa:1,c:1};c.Z=a;c.U=l;c.W=m;c.Ma=null;c.la=d;c.ka=void 0;c.ja=void 0;c.p=void 0;c.name=d;c.isPrimitive=!1;c.isInterface=!1;c.isArrayClass=!0;c.isInstance=function(a){return l.p(a,m)};return c}
function r(a){if(!a.ka){var b=new Ea;b.C=a;a.ka=b}return a.ka}function Fa(a){a.ja||(a.ja=Ba(a));return a.ja}u.prototype.getFakeInstance=function(){return this===ha?"some string":this===pa?!1:this===ja||this===la||this===ma||this===na||this===oa?0:this===sa?Ca().ia:this===qa?void 0:{$classData:this}};u.prototype.getSuperclass=function(){return this.pa?r(this.pa):null};u.prototype.getComponentType=function(){return this.Z?r(this.Z):null};
u.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b=Fa(b);return fa(b,a,0)};var Ga=w(!1,"Z","boolean"),Ha=w(0,"C","char"),Ia=w(0,"B","byte"),Ja=w(0,"S","short"),Ka=w(0,"I","int"),La=w("longZero","J","long"),Ma=w(0,"F","float"),Na=w(0,"D","double");Ga.p=q(Ga);Ha.p=q(Ha);Ia.p=q(Ia);Ja.p=q(Ja);Ka.p=q(Ka);La.p=q(La);Ma.p=q(Ma);Na.p=q(Na);var Oa=require("path"),Pa=require("body-parser"),Qa=require("express");function Ra(){}function y(){}y.prototype=Ra.prototype;Ra.prototype.a=function(){return this};Ra.prototype.f=function(){var a=ga(this).C.name,b=(+(this.o()>>>0)).toString(16);return a+"@"+b};Ra.prototype.o=function(){return xa(this)};Ra.prototype.toString=function(){return this.f()};
var Da=x({b:0},"java.lang.Object",{b:1},void 0,void 0,function(a){return null!==a},function(a,b){if(a=a&&a.$classData){var c=a.W||0;return!(c<b)&&(c>b||!a.U.isPrimitive)}return!1});Ra.prototype.$classData=Da;function Sa(){}Sa.prototype=new y;Sa.prototype.constructor=Sa;Sa.prototype.a=function(){return this};Sa.prototype.$classData=x({yb:0},"io.scalajs.npm.bodyparser.UrlEncodedBodyOptions$",{yb:1,b:1});var Ta=void 0;function Ua(){Ta||(Ta=(new Sa).a())}function Va(){}Va.prototype=new y;
Va.prototype.constructor=Va;Va.prototype.a=function(){return this};Va.prototype.$classData=x({Cb:0},"org.dractec.ftetris.node.ScoreServer$",{Cb:1,b:1});var Wa=void 0;function Ea(){this.C=null}Ea.prototype=new y;Ea.prototype.constructor=Ea;Ea.prototype.f=function(){return(this.C.isInterface?"interface ":this.C.isPrimitive?"":"class ")+this.C.name};Ea.prototype.$classData=x({Nb:0},"java.lang.Class",{Nb:1,b:1});function Xa(){this.Qa=this.$a=null}Xa.prototype=new y;Xa.prototype.constructor=Xa;
Xa.prototype.a=function(){Ya=this;this.$a=Za(!1);this.Qa=Za(!0);return this};Xa.prototype.$classData=x({Zb:0},"java.lang.System$",{Zb:1,b:1});var Ya=void 0;function $a(){Ya||(Ya=(new Xa).a());return Ya}function ab(){}ab.prototype=new y;ab.prototype.constructor=ab;function bb(){}bb.prototype=ab.prototype;function cb(){}cb.prototype=new y;cb.prototype.constructor=cb;function db(){}db.prototype=cb.prototype;function eb(){}eb.prototype=new y;eb.prototype.constructor=eb;eb.prototype.a=function(){return this};
eb.prototype.$classData=x({pc:0},"scala.math.Ordered$",{pc:1,b:1});var fb=void 0;function gb(){}gb.prototype=new y;gb.prototype.constructor=gb;
gb.prototype.a=function(){hb=this;(new z).a();ib||(ib=(new jb).a());kb||(kb=(new lb).a());mb||(mb=(new nb).a());ob();pb();qb||(qb=(new A).a());rb();sb||(sb=(new B).a());tb||(tb=(new ub).a());vb||(vb=(new wb).a());xb||(xb=(new yb).a());zb||(zb=(new Ab).a());Bb||(Bb=(new Cb).a());Db||(Db=(new Eb).a());Fb||(Fb=(new Gb).a());Hb||(Hb=(new Ib).a());Jb||(Jb=(new Kb).a());Lb||(Lb=(new Mb).a());Nb||(Nb=(new Ob).a());fb||(fb=(new eb).a());Pb||(Pb=(new Qb).a());Rb||(Rb=(new Sb).a());Tb||(Tb=(new C).a());Ub||
(Ub=(new D).a());return this};gb.prototype.$classData=x({rc:0},"scala.package$",{rc:1,b:1});var hb=void 0;function Vb(){}Vb.prototype=new y;Vb.prototype.constructor=Vb;
Vb.prototype.a=function(){Wb=this;Xb||(Xb=(new Yb).a());Zb||(Zb=(new $b).a());ac||(ac=(new bc).a());cc||(cc=(new dc).a());ec||(ec=(new fc).a());gc||(gc=(new hc).a());ic||(ic=(new jc).a());kc||(kc=(new lc).a());mc||(mc=(new nc).a());oc||(oc=(new pc).a());qc||(qc=(new rc).a());sc||(sc=(new tc).a());uc||(uc=(new vc).a());wc||(wc=(new xc).a());return this};Vb.prototype.$classData=x({tc:0},"scala.reflect.ClassManifestFactory$",{tc:1,b:1});var Wb=void 0;function yc(){}yc.prototype=new y;
yc.prototype.constructor=yc;yc.prototype.a=function(){return this};yc.prototype.$classData=x({uc:0},"scala.reflect.ManifestFactory$",{uc:1,b:1});var zc=void 0;function E(){}E.prototype=new y;E.prototype.constructor=E;E.prototype.a=function(){Ac=this;Wb||(Wb=(new Vb).a());zc||(zc=(new yc).a());return this};E.prototype.$classData=x({Kc:0},"scala.reflect.package$",{Kc:1,b:1});var Ac=void 0;function F(){this.wa=null}F.prototype=new y;F.prototype.constructor=F;
F.prototype.f=function(){return"DynamicVariable("+this.wa+")"};F.prototype.ba=function(a){this.wa=a;return this};F.prototype.$classData=x({Lc:0},"scala.util.DynamicVariable",{Lc:1,b:1});function Bc(){}Bc.prototype=new y;Bc.prototype.constructor=Bc;Bc.prototype.a=function(){(new G).a();return this};Bc.prototype.$classData=x({Qc:0},"scala.util.control.Breaks",{Qc:1,b:1});function Cc(){}Cc.prototype=new y;Cc.prototype.constructor=Cc;function Dc(){}Dc.prototype=Cc.prototype;
function Ec(a,b){b=k(-862048943,b);b=k(461845907,b<<15|b>>>17|0);a^=b;return-430675100+k(5,a<<13|a>>>19|0)|0}function Fc(a){a=k(-2048144789,a^(a>>>16|0));a=k(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)}function Gc(a){Hc();var b=a.ea();if(0===b)return a=a.ga(),ua(t(),a);for(var c=-889275714,d=0;d<b;)c=Ec(c,Ic(Jc(),a.fa(d))),d=1+d|0;return Fc(c^b)}
function Kc(a,b,c){var d=(new H).$(0);c=(new H).$(c);b.I(Lc(function(a,b,c){return function(a){c.k=Ec(c.k,Ic(Jc(),a));b.k=1+b.k|0}}(a,d,c)));return Fc(c.k^d.k)}function wb(){}wb.prototype=new y;wb.prototype.constructor=wb;wb.prototype.a=function(){return this};wb.prototype.$classData=x({Tc:0},"scala.collection.$colon$plus$",{Tc:1,b:1});var vb=void 0;function ub(){}ub.prototype=new y;ub.prototype.constructor=ub;ub.prototype.a=function(){return this};
ub.prototype.$classData=x({Uc:0},"scala.collection.$plus$colon$",{Uc:1,b:1});var tb=void 0;function Mc(){this.Aa=null}Mc.prototype=new y;Mc.prototype.constructor=Mc;Mc.prototype.a=function(){Nc=this;this.Aa=(new I).a();return this};Mc.prototype.$classData=x({bd:0},"scala.collection.Iterator$",{bd:1,b:1});var Nc=void 0;function pb(){Nc||(Nc=(new Mc).a());return Nc}function Oc(a,b,c){return a.Oa((new J).a(),b,c,")").w.e}
function Pc(a,b,c,d,g){var l=Qc();Rc(b,c);a.I(Lc(function(a,b,c,d){return function(a){if(d.k)Sc(b,a),d.k=!1;else return Rc(b,c),Sc(b,a)}}(a,b,d,l)));Rc(b,g);return b}function Tc(){}Tc.prototype=new y;Tc.prototype.constructor=Tc;function Uc(){}Uc.prototype=Tc.prototype;function Vc(){}Vc.prototype=new y;Vc.prototype.constructor=Vc;function Wc(){}Wc.prototype=Vc.prototype;function Ab(){}Ab.prototype=new y;Ab.prototype.constructor=Ab;Ab.prototype.a=function(){return this};
Ab.prototype.$classData=x({ud:0},"scala.collection.immutable.Stream$$hash$colon$colon$",{ud:1,b:1});var zb=void 0;function Xc(){this.Ea=null}Xc.prototype=new y;Xc.prototype.constructor=Xc;Xc.prototype.a=function(){Yc=this;this.Ea=h.Object.prototype.hasOwnProperty;return this};Xc.prototype.$classData=x({Id:0},"scala.scalajs.js.WrappedDictionary$Cache$",{Id:1,b:1});var Yc=void 0;function Zc(){Yc||(Yc=(new Xc).a());return Yc}
function $c(){this.D=!1;this.Sa=this.oa=this.V=null;this.ya=!1;this.Za=this.Ua=0}$c.prototype=new y;$c.prototype.constructor=$c;
$c.prototype.a=function(){ad=this;this.V=(this.D=!!(h.ArrayBuffer&&h.Int32Array&&h.Float32Array&&h.Float64Array))?new h.ArrayBuffer(8):null;this.oa=this.D?new h.Int32Array(this.V,0,2):null;this.D&&new h.Float32Array(this.V,0,2);this.Sa=this.D?new h.Float64Array(this.V,0,1):null;if(this.D)this.oa[0]=16909060,a=1===((new h.Int8Array(this.V,0,8))[0]|0);else var a=!0;this.Ua=(this.ya=a)?0:1;this.Za=this.ya?1:0;return this};
function va(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;if(a.D)a.Sa[0]=b,a=(new K).aa(a.oa[a.Za]|0,a.oa[a.Ua]|0);else{if(b!==b)a=!1,b=2047,c=+h.Math.pow(2,51);else if(Infinity===b||-Infinity===b)a=0>b,b=2047,c=0;else if(0===b)a=-Infinity===1/b,c=b=0;else{var d=(a=0>b)?-b:b;if(d>=+h.Math.pow(2,-1022)){b=+h.Math.pow(2,52);var c=+h.Math.log(d)/.6931471805599453,c=+h.Math.floor(c)|0,c=1023>c?c:1023,g=+h.Math.pow(2,c);g>d&&(c=-1+c|0,g/=2);g=d/g*b;d=+h.Math.floor(g);g-=d;d=.5>g?d:.5<g?1+d:0!==d%2?
1+d:d;2<=d/b&&(c=1+c|0,d=1);1023<c?(c=2047,d=0):(c=1023+c|0,d-=b);b=c;c=d}else b=d/+h.Math.pow(2,-1074),c=+h.Math.floor(b),d=b-c,b=0,c=.5>d?c:.5<d?1+c:0!==c%2?1+c:c}c=+c;a=(new K).aa(c|0,(a?-2147483648:0)|(b|0)<<20|c/4294967296|0)}return a.O^a.J}$c.prototype.$classData=x({Kd:0},"scala.scalajs.runtime.Bits$",{Kd:1,b:1});var ad=void 0;function wa(){ad||(ad=(new $c).a());return ad}function bd(){}bd.prototype=new y;bd.prototype.constructor=bd;
function cd(a,b){return"/app"===b.substring((b.length|0)-4|0)}bd.prototype.a=function(){return this};function dd(){return h.String.fromCharCode(92)}function ua(a,b){a=0;for(var c=1,d=-1+(b.length|0)|0;0<=d;)a=a+k(65535&(b.charCodeAt(d)|0),c)|0,c=k(31,c),d=-1+d|0;return a}bd.prototype.$classData=x({Md:0},"scala.scalajs.runtime.RuntimeString$",{Md:1,b:1});var ed=void 0;function t(){ed||(ed=(new bd).a());return ed}function fd(){}fd.prototype=new y;fd.prototype.constructor=fd;fd.prototype.a=function(){return this};
function gd(a,b){return b&&b.$classData&&b.$classData.s.Ia?b.H:b}fd.prototype.$classData=x({Nd:0},"scala.scalajs.runtime.package$",{Nd:1,b:1});var hd=void 0;function id(){hd||(hd=(new fd).a());return hd}var jd=x({Sd:0},"scala.runtime.Null$",{Sd:1,b:1});function kd(){}kd.prototype=new y;kd.prototype.constructor=kd;kd.prototype.a=function(){return this};kd.prototype.$classData=x({Td:0},"scala.runtime.ScalaRunTime$",{Td:1,b:1});var ld=void 0;function md(){}md.prototype=new y;
md.prototype.constructor=md;md.prototype.a=function(){return this};
function Ic(a,b){if(null===b)return 0;if("number"===typeof b){a=+b;b=2147483647<a?2147483647:-2147483648>a?-2147483648:a|0;if(b===a)a=b;else{b=Ca();var c;if(-9223372036854775808>a)b.ta=-2147483648,c=0;else if(0x7fffffffffffffff<=a)b.ta=2147483647,c=-1;else{c=a|0;var d=a/4294967296|0;b.ta=0>a&&0!==c?-1+d|0:d}b=b.ta;Ca();a=(0>b?-(4294967296*+((0!==c?~b:-b|0)>>>0)+ +((-c|0)>>>0)):4294967296*b+ +(c>>>0))===a?c^b:va(wa(),a)}return a}return ra(b)?(a=null===b?Ca().ia:b,b=(new K).aa(a.O,a.J),a=b.O,b=b.J,
b===a>>31?a:a^b):ta(b)}md.prototype.$classData=x({Vd:0},"scala.runtime.Statics$",{Vd:1,b:1});var nd=void 0;function Jc(){nd||(nd=(new md).a());return nd}function od(){}od.prototype=new y;od.prototype.constructor=od;function pd(){}pd.prototype=od.prototype;function L(){this.q=null}L.prototype=new y;L.prototype.constructor=L;function qd(){}qd.prototype=L.prototype;
L.prototype.ma=function(){if(void 0===h.Error.captureStackTrace){try{var a={}.undef()}catch(b){if(id(),a=b&&b.$classData&&b.$classData.s.z?b:(new rd).ba(b),null!==a)if(a&&a.$classData&&a.$classData.s.Ia)a=a.H;else throw gd(id(),a);else throw b;}this.stackdata=a}else h.Error.captureStackTrace(this),this.stackdata=this;return this};L.prototype.Ta=function(){return this.q};L.prototype.f=function(){var a=ga(this).C.name,b=this.Ta();return null===b?a:a+": "+b};
L.prototype.y=function(a){this.q=a;this.ma();return this};function sd(){}sd.prototype=new y;sd.prototype.constructor=sd;sd.prototype.a=function(){return this};sd.prototype.$classData=x({hc:0},"scala.Predef$$anon$3",{hc:1,b:1,rb:1});function z(){}z.prototype=new y;z.prototype.constructor=z;z.prototype.a=function(){return this};z.prototype.f=function(){return"object AnyRef"};z.prototype.$classData=x({sc:0},"scala.package$$anon$1",{sc:1,b:1,ge:1});function td(){this.Ha=0}td.prototype=new Dc;
td.prototype.constructor=td;td.prototype.a=function(){ud=this;this.Ha=ua(t(),"Seq");ua(t(),"Map");ua(t(),"Set");return this};function vd(a){var b=Hc();return a&&a.$classData&&a.$classData.s.md?Fc(b.Ha^0):Kc(b,a,b.Ha)}td.prototype.$classData=x({Sc:0},"scala.util.hashing.MurmurHash3$",{Sc:1,ne:1,b:1});var ud=void 0;function Hc(){ud||(ud=(new td).a());return ud}function wd(){}wd.prototype=new Wc;wd.prototype.constructor=wd;function xd(){}xd.prototype=wd.prototype;function M(){}M.prototype=new Wc;
M.prototype.constructor=M;function yd(){}yd.prototype=M.prototype;M.prototype.a=function(){(new zd).na(this);return this};function N(){}N.prototype=new y;N.prototype.constructor=N;function Ad(){}Ad.prototype=N.prototype;N.prototype.na=function(a){if(null===a)throw gd(id(),null);return this};function Bd(){}Bd.prototype=new Uc;Bd.prototype.constructor=Bd;function Cd(){}Cd.prototype=Bd.prototype;function O(){}O.prototype=new y;O.prototype.constructor=O;O.prototype.a=function(){return this};
O.prototype.x=function(){return this};O.prototype.f=function(){return"\x3cfunction1\x3e"};O.prototype.$classData=x({od:0},"scala.collection.immutable.List$$anon$1",{od:1,b:1,G:1});function Dd(){}Dd.prototype=new y;Dd.prototype.constructor=Dd;function Ed(){}Ed.prototype=Dd.prototype;Dd.prototype.f=function(){return"\x3cfunction1\x3e"};function Fd(){this.k=!1}Fd.prototype=new y;Fd.prototype.constructor=Fd;Fd.prototype.f=function(){return""+this.k};function Qc(){var a=new Fd;a.k=!0;return a}
Fd.prototype.$classData=x({Od:0},"scala.runtime.BooleanRef",{Od:1,b:1,c:1});var qa=x({Pd:0},"scala.runtime.BoxedUnit",{Pd:1,b:1,c:1},void 0,void 0,function(a){return void 0===a});function H(){this.k=0}H.prototype=new y;H.prototype.constructor=H;H.prototype.f=function(){return""+this.k};H.prototype.$=function(a){this.k=a;return this};H.prototype.$classData=x({Qd:0},"scala.runtime.IntRef",{Qd:1,b:1,c:1});var Gd=void 0;
function Hd(){if(!Gd){var a=function(){for(var a=arguments.length|0,b=0,g=[];b<a;)g.push(arguments[b]),b=b+1|0;void 0===g[0]?(Ua(),a=void 0):a=g[0];void 0===g[1]?(Ua(),b=void 0):b=g[1];var l;void 0===g[2]?(Ua(),l=void 0):l=g[2];var m;void 0===g[3]?(Ua(),m=void 0):m=g[3];var p;void 0===g[4]?(Ua(),p=void 0):p=g[4];void 0===g[5]?(Ua(),g=void 0):g=g[5];h.Object.call(this);h.Object.defineProperty(this,"extended",{configurable:!0,enumerable:!0,writable:!0,value:null});h.Object.defineProperty(this,"inflate",
{configurable:!0,enumerable:!0,writable:!0,value:null});h.Object.defineProperty(this,"limit",{configurable:!0,enumerable:!0,writable:!0,value:null});h.Object.defineProperty(this,"parameterLimit",{configurable:!0,enumerable:!0,writable:!0,value:null});h.Object.defineProperty(this,"type",{configurable:!0,enumerable:!0,writable:!0,value:null});h.Object.defineProperty(this,"verify",{configurable:!0,enumerable:!0,writable:!0,value:null});this.extended=a;this.inflate=b;this.limit=l;this.parameterLimit=
m;this.type=p;this.verify=g},b=function(){};b.prototype=h.Object.prototype;a.prototype=new b;Gd=a.prototype.constructor=a}return Gd}var pa=x({Kb:0},"java.lang.Boolean",{Kb:1,b:1,c:1,t:1},void 0,void 0,function(a){return"boolean"===typeof a});function P(){this.La=0}P.prototype=new y;P.prototype.constructor=P;P.prototype.f=function(){return h.String.fromCharCode(this.La)};function Id(a){var b=new P;b.La=a;return b}P.prototype.o=function(){return this.La};
P.prototype.$classData=x({Mb:0},"java.lang.Character",{Mb:1,b:1,c:1,t:1});function Jd(){this.q=null}Jd.prototype=new qd;Jd.prototype.constructor=Jd;function Kd(){}Kd.prototype=Jd.prototype;function Ld(){this.Ca=null}Ld.prototype=new bb;Ld.prototype.constructor=Ld;Ld.prototype.a=function(){Md=this;this.Ca=(new F).ba($a().$a);(new F).ba($a().Qa);(new F).ba(null);return this};Ld.prototype.$classData=x({bc:0},"scala.Console$",{bc:1,$d:1,b:1,he:1});var Md=void 0;
function Nd(){Md||(Md=(new Ld).a());return Md}function Od(){}Od.prototype=new db;Od.prototype.constructor=Od;Od.prototype.a=function(){Pd=this;hb||(hb=(new gb).a());qb||(qb=(new A).a());Qd||(Qd=(new Rd).a());Sd||(Sd=(new Td).a());Ac||(Ac=(new E).a());Ac||(Ac=(new E).a());Ud||(Ud=(new Q).a());(new sd).a();(new R).a();(new Vd).a();return this};Od.prototype.$classData=x({ec:0},"scala.Predef$",{ec:1,ce:1,b:1,ae:1});var Pd=void 0;function Wd(){}Wd.prototype=new y;Wd.prototype.constructor=Wd;
Wd.prototype.a=function(){return this};Wd.prototype.$classData=x({jc:0},"scala.StringContext$",{jc:1,b:1,d:1,c:1});var Xd=void 0;function Kb(){}Kb.prototype=new y;Kb.prototype.constructor=Kb;Kb.prototype.a=function(){return this};Kb.prototype.$classData=x({mc:0},"scala.math.Fractional$",{mc:1,b:1,d:1,c:1});var Jb=void 0;function Mb(){}Mb.prototype=new y;Mb.prototype.constructor=Mb;Mb.prototype.a=function(){return this};Mb.prototype.$classData=x({nc:0},"scala.math.Integral$",{nc:1,b:1,d:1,c:1});
var Lb=void 0;function Ob(){}Ob.prototype=new y;Ob.prototype.constructor=Ob;Ob.prototype.a=function(){return this};Ob.prototype.$classData=x({oc:0},"scala.math.Numeric$",{oc:1,b:1,d:1,c:1});var Nb=void 0;function Sb(){}Sb.prototype=new y;Sb.prototype.constructor=Sb;Sb.prototype.a=function(){return this};Sb.prototype.$classData=x({Mc:0},"scala.util.Either$",{Mc:1,b:1,d:1,c:1});var Rb=void 0;function C(){}C.prototype=new y;C.prototype.constructor=C;C.prototype.a=function(){return this};
C.prototype.f=function(){return"Left"};C.prototype.$classData=x({Nc:0},"scala.util.Left$",{Nc:1,b:1,d:1,c:1});var Tb=void 0;function D(){}D.prototype=new y;D.prototype.constructor=D;D.prototype.a=function(){return this};D.prototype.f=function(){return"Right"};D.prototype.$classData=x({Oc:0},"scala.util.Right$",{Oc:1,b:1,d:1,c:1});var Ub=void 0;function Yd(){this.Na=!1}Yd.prototype=new y;Yd.prototype.constructor=Yd;Yd.prototype.a=function(){this.Na=!1;return this};
Yd.prototype.$classData=x({Rc:0},"scala.util.control.NoStackTrace$",{Rc:1,b:1,d:1,c:1});var Zd=void 0;function $d(){}$d.prototype=new Ad;$d.prototype.constructor=$d;$d.prototype.a=function(){N.prototype.na.call(this,ob());return this};$d.prototype.$classData=x({Xc:0},"scala.collection.IndexedSeq$$anon$1",{Xc:1,id:1,b:1,rb:1});function ae(){}ae.prototype=new yd;ae.prototype.constructor=ae;function be(){}be.prototype=ae.prototype;function zd(){this.ha=null}zd.prototype=new Ad;
zd.prototype.constructor=zd;zd.prototype.na=function(a){if(null===a)throw gd(id(),null);this.ha=a;N.prototype.na.call(this,a);return this};zd.prototype.$classData=x({hd:0},"scala.collection.generic.GenTraversableFactory$$anon$1",{hd:1,id:1,b:1,rb:1});function ce(){}ce.prototype=new Cd;ce.prototype.constructor=ce;function de(){}de.prototype=ce.prototype;function B(){}B.prototype=new y;B.prototype.constructor=B;B.prototype.a=function(){return this};B.prototype.f=function(){return"::"};
B.prototype.$classData=x({ld:0},"scala.collection.immutable.$colon$colon$",{ld:1,b:1,d:1,c:1});var sb=void 0;function Gb(){}Gb.prototype=new y;Gb.prototype.constructor=Gb;Gb.prototype.a=function(){return this};Gb.prototype.$classData=x({rd:0},"scala.collection.immutable.Range$",{rd:1,b:1,d:1,c:1});var Fb=void 0;function Eb(){}Eb.prototype=new y;Eb.prototype.constructor=Eb;Eb.prototype.a=function(){return this};
Eb.prototype.$classData=x({Fd:0},"scala.collection.mutable.StringBuilder$",{Fd:1,b:1,d:1,c:1});var Db=void 0;function ee(){this.Ra=null}ee.prototype=new Ed;ee.prototype.constructor=ee;ee.prototype.x=function(a){return(0,this.Ra)(a)};function Lc(a){var b=new ee;b.Ra=a;return b}ee.prototype.$classData=x({Jd:0},"scala.scalajs.runtime.AnonFunction1",{Jd:1,Me:1,b:1,G:1});function fe(){this.ta=0;this.ia=null}fe.prototype=new y;fe.prototype.constructor=fe;
fe.prototype.a=function(){ge=this;this.ia=(new K).aa(0,0);return this};
function he(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+ba(1E9)|0)-(0!==b?ba(b):32+ba(a)|0)|0,d=c,g=0===(32&d)?1E9<<d:0,d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d,l=a,m=b;for(a=b=0;0<=c&&0!==(-2097152&m);){var p=l,v=m,nf=g,n=d;if(v===n?(-2147483648^p)>=(-2147483648^nf):(-2147483648^v)>=(-2147483648^n))p=m,v=d,m=l-g|0,p=(-2147483648^m)>(-2147483648^l)?-1+(p-v|0)|0:p-v|0,l=m,m=p,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;p=d>>>1|0;g=g>>>1|0|d<<31;d=p}c=m;if(0===c?-1147483648<=(-2147483648^
l):-2147483648<=(-2147483648^c))c=4294967296*m+ +(l>>>0),l=c/1E9,g=l/4294967296|0,d=b,b=l=d+(l|0)|0,a=(-2147483648^l)<(-2147483648^d)?1+(a+g|0)|0:a+g|0,l=c%1E9|0;c=""+l;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length|0)+c}return b}fe.prototype.$classData=x({Ld:0},"scala.scalajs.runtime.RuntimeLong$",{Ld:1,b:1,d:1,c:1});var ge=void 0;function Ca(){ge||(ge=(new fe).a());return ge}var ie=x({Rd:0},"scala.runtime.Nothing$",{Rd:1,z:1,b:1,c:1});function je(){}je.prototype=new y;
je.prototype.constructor=je;function ke(){}ke.prototype=je.prototype;
var ha=x({Db:0},"java.lang.String",{Db:1,b:1,c:1,Wa:1,t:1},void 0,void 0,function(a){return"string"===typeof a}),ja=x({Lb:0},"java.lang.Byte",{Lb:1,M:1,b:1,c:1,t:1},void 0,void 0,function(a){return ia(a)}),oa=x({Ob:0},"java.lang.Double",{Ob:1,M:1,b:1,c:1,t:1},void 0,void 0,function(a){return"number"===typeof a}),na=x({Pb:0},"java.lang.Float",{Pb:1,M:1,b:1,c:1,t:1},void 0,void 0,function(a){return"number"===typeof a}),ma=x({Rb:0},"java.lang.Integer",{Rb:1,M:1,b:1,c:1,t:1},void 0,void 0,function(a){return"number"===
typeof a&&(a|0)===a&&1/a!==1/-0}),sa=x({Ub:0},"java.lang.Long",{Ub:1,M:1,b:1,c:1,t:1},void 0,void 0,function(a){return ra(a)});function le(){this.q=null}le.prototype=new Kd;le.prototype.constructor=le;function me(){}me.prototype=le.prototype;var la=x({Xb:0},"java.lang.Short",{Xb:1,M:1,b:1,c:1,t:1},void 0,void 0,function(a){return ka(a)});function S(){this.e=null}S.prototype=new y;S.prototype.constructor=S;e=S.prototype;e.a=function(){this.e="";return this};
e.wb=function(a,b){return this.e.substring(a,b)};e.f=function(){return this.e};e.$=function(a){S.prototype.a.call(this);if(0>a)throw(new ne).a();return this};function oe(a,b,c,d){b=null===b?"null":b;c="string"===typeof b?b.substring(c,d):b.wb(c,d);a.e=""+a.e+c}e.u=function(){return this.e.length|0};e.i=function(a){S.prototype.a.call(this);if(null===a)throw(new pe).a();this.e=a;return this};e.$classData=x({Yb:0},"java.lang.StringBuilder",{Yb:1,b:1,Wa:1,Ib:1,c:1});function qe(){}qe.prototype=new y;
qe.prototype.constructor=qe;function re(){}re.prototype=qe.prototype;qe.prototype.f=function(){return"\x3cfunction1\x3e"};function se(){}se.prototype=new y;se.prototype.constructor=se;function te(){}te.prototype=se.prototype;se.prototype.f=function(){return"\x3cfunction1\x3e"};function Ib(){}Ib.prototype=new y;Ib.prototype.constructor=Ib;Ib.prototype.a=function(){return this};Ib.prototype.$classData=x({lc:0},"scala.math.Equiv$",{lc:1,b:1,ie:1,d:1,c:1});var Hb=void 0;function Qb(){}Qb.prototype=new y;
Qb.prototype.constructor=Qb;Qb.prototype.a=function(){return this};Qb.prototype.$classData=x({qc:0},"scala.math.Ordering$",{qc:1,b:1,je:1,d:1,c:1});var Pb=void 0;function Q(){}Q.prototype=new y;Q.prototype.constructor=Q;Q.prototype.a=function(){return this};Q.prototype.f=function(){return"\x3c?\x3e"};Q.prototype.$classData=x({Jc:0},"scala.reflect.NoManifest$",{Jc:1,b:1,j:1,d:1,c:1});var Ud=void 0;function ue(){}ue.prototype=new y;ue.prototype.constructor=ue;function ve(){}ve.prototype=ue.prototype;
ue.prototype.f=function(){return(this.A()?"non-empty":"empty")+" iterator"};ue.prototype.I=function(a){for(;this.A();)a.x(this.v())};ue.prototype.Oa=function(a,b,c,d){return Pc(this,a,b,c,d)};function we(){}we.prototype=new xd;we.prototype.constructor=we;function xe(){}xe.prototype=we.prototype;function Rd(){}Rd.prototype=new de;Rd.prototype.constructor=Rd;Rd.prototype.a=function(){return this};Rd.prototype.$classData=x({pd:0},"scala.collection.immutable.Map$",{pd:1,ve:1,xe:1,te:1,b:1});var Qd=void 0;
function K(){this.J=this.O=0}K.prototype=new pd;K.prototype.constructor=K;e=K.prototype;e.f=function(){Ca();var a=this.O,b=this.J;return b===a>>31?""+a:0>b?"-"+he(-a|0,0!==a?~b:-b|0):he(a,b)};e.aa=function(a,b){this.O=a;this.J=b;return this};e.$=function(a){K.prototype.aa.call(this,a,a>>31);return this};e.o=function(){return this.O^this.J};function ra(a){return!!(a&&a.$classData&&a.$classData.s.vb)}e.$classData=x({vb:0},"scala.scalajs.runtime.RuntimeLong",{vb:1,M:1,b:1,c:1,t:1});function ye(){}
ye.prototype=new ke;ye.prototype.constructor=ye;function ze(){}ze.prototype=ye.prototype;ye.prototype.Fb=function(){return this};function T(){this.q=null}T.prototype=new me;T.prototype.constructor=T;function Ae(){}Ae.prototype=T.prototype;T.prototype.a=function(){L.prototype.y.call(this,null);return this};T.prototype.i=function(a){L.prototype.y.call(this,a);return this};T.prototype.$classData=x({Ya:0},"java.lang.IllegalArgumentException",{Ya:1,N:1,L:1,z:1,b:1,c:1});function U(){this.q=null}
U.prototype=new me;U.prototype.constructor=U;U.prototype.i=function(a){L.prototype.y.call(this,a);return this};U.prototype.$classData=x({Qb:0},"java.lang.IndexOutOfBoundsException",{Qb:1,N:1,L:1,z:1,b:1,c:1});function Be(){}Be.prototype=new ke;Be.prototype.constructor=Be;Be.prototype.a=function(){return this};Be.prototype.$classData=x({Tb:0},"java.lang.JSConsoleBasedPrintStream$DummyOutputStream",{Tb:1,Bb:1,b:1,zb:1,Jb:1,Ab:1});function ne(){this.q=null}ne.prototype=new me;
ne.prototype.constructor=ne;ne.prototype.a=function(){L.prototype.y.call(this,null);return this};ne.prototype.$classData=x({Vb:0},"java.lang.NegativeArraySizeException",{Vb:1,N:1,L:1,z:1,b:1,c:1});function pe(){this.q=null}pe.prototype=new me;pe.prototype.constructor=pe;pe.prototype.a=function(){L.prototype.y.call(this,null);return this};pe.prototype.$classData=x({Wb:0},"java.lang.NullPointerException",{Wb:1,N:1,L:1,z:1,b:1,c:1});function V(){this.q=null}V.prototype=new me;
V.prototype.constructor=V;V.prototype.i=function(a){L.prototype.y.call(this,a);return this};V.prototype.$classData=x({$b:0},"java.util.NoSuchElementException",{$b:1,N:1,L:1,z:1,b:1,c:1});function Ce(){}Ce.prototype=new y;Ce.prototype.constructor=Ce;function De(){}De.prototype=Ce.prototype;function R(){}R.prototype=new te;R.prototype.constructor=R;R.prototype.a=function(){return this};R.prototype.x=function(a){return a};
R.prototype.$classData=x({fc:0},"scala.Predef$$anon$1",{fc:1,fe:1,b:1,G:1,d:1,c:1});function Vd(){}Vd.prototype=new re;Vd.prototype.constructor=Vd;Vd.prototype.a=function(){return this};Vd.prototype.x=function(a){return a};Vd.prototype.$classData=x({gc:0},"scala.Predef$$anon$2",{gc:1,ee:1,b:1,G:1,d:1,c:1});function W(){this.da=null}W.prototype=new y;W.prototype.constructor=W;e=W.prototype;e.ga=function(){return"StringContext"};e.ea=function(){return 1};
e.fa=function(a){switch(a){case 0:return this.da;default:throw(new U).i(""+a);}};e.f=function(){ld||(ld=(new kd).a());var a=this.qa();return Oc(a,this.ga()+"(",",")};
function Ee(a,b){var c=function(){return function(a){Xd||(Xd=(new Wd).a());a:{var b=a.length|0,c;t();var d=dd();c=a.indexOf(d)|0;switch(c){case -1:break a;default:d=(new S).a();b:{var g=c;c=0;for(;;)if(0<=g){g>c&&oe(d,a,c,g);c=1+g|0;if(c>=b)throw Fe(a,g);var n=65535&(a.charCodeAt(c)|0);switch(n){case 98:n=8;break;case 116:n=9;break;case 110:n=10;break;case 102:n=12;break;case 114:n=13;break;case 34:n=34;break;case 39:n=39;break;case 92:n=92;break;default:if(48<=n&&55>=n)g=65535&(a.charCodeAt(c)|0),
n=-48+g|0,c=1+c|0,c<b&&48<=(65535&(a.charCodeAt(c)|0))&&55>=(65535&(a.charCodeAt(c)|0))&&(n=-48+((n<<3)+(65535&(a.charCodeAt(c)|0))|0)|0,c=1+c|0,c<b&&51>=g&&48<=(65535&(a.charCodeAt(c)|0))&&55>=(65535&(a.charCodeAt(c)|0))&&(n=-48+((n<<3)+(65535&(a.charCodeAt(c)|0))|0)|0,c=1+c|0)),c=-1+c|0,n&=65535;else throw Fe(a,g);}c=1+c|0;g=d;n=h.String.fromCharCode(n);g.e=""+g.e+n;g=c;t();var n=a,wf=dd(),n=n.indexOf(wf,c)|0;c=g;g=n}else{c<b&&oe(d,a,c,b);a=d.e;break b}}}}return a}}(a);if(a.da.u()!==(1+b.u()|0))throw(new T).i("wrong number of arguments ("+
b.u()+") for interpolated string with "+a.da.u()+" parts");a=a.da.ca();b=b.ca();for(var d=a.v(),d=(new S).i(c(d));b.A();){var g=b.v();d.e=""+d.e+g;g=a.v();g=c(g);d.e=""+d.e+g}return d.e}function Ge(a,b){a.da=b;return a}e.o=function(){return Gc(this)};e.qa=function(){return He(this)};e.$classData=x({ic:0},"scala.StringContext",{ic:1,b:1,Da:1,g:1,d:1,c:1});function G(){this.q=null}G.prototype=new qd;G.prototype.constructor=G;G.prototype.a=function(){L.prototype.y.call(this,null);return this};
G.prototype.ma=function(){Zd||(Zd=(new Yd).a());return Zd.Na?L.prototype.ma.call(this):this};G.prototype.$classData=x({Pc:0},"scala.util.control.BreakControl",{Pc:1,z:1,b:1,c:1,le:1,me:1});function lb(){}lb.prototype=new yd;lb.prototype.constructor=lb;lb.prototype.a=function(){M.prototype.a.call(this);return this};lb.prototype.$classData=x({ad:0},"scala.collection.Iterable$",{ad:1,R:1,E:1,b:1,S:1,F:1});var kb=void 0;function I(){}I.prototype=new ve;I.prototype.constructor=I;I.prototype.a=function(){return this};
I.prototype.v=function(){throw(new V).i("next on empty iterator");};I.prototype.A=function(){return!1};I.prototype.$classData=x({cd:0},"scala.collection.Iterator$$anon$2",{cd:1,Fa:1,b:1,Ga:1,Q:1,P:1});function Ie(){this.Wd=null}Ie.prototype=new ve;Ie.prototype.constructor=Ie;Ie.prototype.v=function(){if(this.A())throw(new V).i("head of empty list");return pb().Aa.v()};Ie.prototype.A=function(){return!1};
Ie.prototype.$classData=x({dd:0},"scala.collection.LinearSeqLike$$anon$1",{dd:1,Fa:1,b:1,Ga:1,Q:1,P:1});function jb(){}jb.prototype=new yd;jb.prototype.constructor=jb;jb.prototype.a=function(){M.prototype.a.call(this);ib=this;(new Bc).a();return this};jb.prototype.$classData=x({fd:0},"scala.collection.Traversable$",{fd:1,R:1,E:1,b:1,S:1,F:1});var ib=void 0;function Je(){}Je.prototype=new xe;Je.prototype.constructor=Je;function Ke(){}Ke.prototype=Je.prototype;
function Le(){this.Pa=this.Y=0;this.xb=null}Le.prototype=new ve;Le.prototype.constructor=Le;Le.prototype.v=function(){var a=this.xb.fa(this.Y);this.Y=1+this.Y|0;return a};function He(a){var b=new Le;b.xb=a;b.Y=0;b.Pa=a.ea();return b}Le.prototype.A=function(){return this.Y<this.Pa};Le.prototype.$classData=x({Ud:0},"scala.runtime.ScalaRunTime$$anon$1",{Ud:1,Fa:1,b:1,Ga:1,Q:1,P:1});function Me(){}Me.prototype=new De;Me.prototype.constructor=Me;e=Me.prototype;e.a=function(){return this};e.ga=function(){return"None"};
e.ea=function(){return 0};e.fa=function(a){throw(new U).i(""+a);};e.f=function(){return"None"};e.o=function(){return 2433880};e.qa=function(){return He(this)};e.$classData=x({dc:0},"scala.None$",{dc:1,de:1,b:1,Da:1,g:1,d:1,c:1});var Ne=void 0;function Oe(){Ne||(Ne=(new Me).a())}function Pe(){this.q=null}Pe.prototype=new Ae;Pe.prototype.constructor=Pe;
function Fe(a,b){var c=new Pe,d=Ge(new W,X(new Y,["invalid escape "," index ",' in "','". Use \\\\\\\\ for literal \\\\.']));Pd||(Pd=(new Od).a());if(!(0<=b&&b<(a.length|0)))throw(new T).i("requirement failed");if(b===(-1+(a.length|0)|0))var g="at terminal";else var g=Ge(new W,X(new Y,["'\\\\","' not one of "," at"])),l=65535&(a.charCodeAt(1+b|0)|0),g=Ee(g,X(new Y,[Id(l),"[\\b, \\t, \\n, \\f, \\r, \\\\, \\\", \\']"]));a=Ee(d,X(new Y,[g,b,a]));L.prototype.y.call(c,a);return c}
Pe.prototype.$classData=x({kc:0},"scala.StringContext$InvalidEscapeException",{kc:1,Ya:1,N:1,L:1,z:1,b:1,c:1});function Qe(){}Qe.prototype=new be;Qe.prototype.constructor=Qe;function Re(){}Re.prototype=Qe.prototype;function Td(){}Td.prototype=new Ke;Td.prototype.constructor=Td;Td.prototype.a=function(){return this};Td.prototype.$classData=x({sd:0},"scala.collection.immutable.Set$",{sd:1,we:1,ye:1,ue:1,E:1,b:1,F:1});var Sd=void 0;function Se(){}Se.prototype=new ze;Se.prototype.constructor=Se;
function Te(){}Te.prototype=Se.prototype;Se.prototype.Gb=function(){ye.prototype.Fb.call(this);return this};function nb(){}nb.prototype=new Re;nb.prototype.constructor=nb;nb.prototype.a=function(){M.prototype.a.call(this);return this};nb.prototype.$classData=x({ed:0},"scala.collection.Seq$",{ed:1,va:1,ua:1,R:1,E:1,b:1,S:1,F:1});var mb=void 0;function Ue(){}Ue.prototype=new Re;Ue.prototype.constructor=Ue;function Ve(){}Ve.prototype=Ue.prototype;function We(){this.X=this.Va=null}We.prototype=new Te;
We.prototype.constructor=We;function Za(a){var b=new We;b.Va=a;(new Be).a();Se.prototype.Gb.call(b);b.X="";return b}function Xe(a,b){for(;""!==b;){var c=b.indexOf("\n")|0;if(0>c)a.X=""+a.X+b,b="";else{var d=""+a.X+b.substring(0,c);h.console&&(a.Va&&h.console.error?h.console.error(d):h.console.log(d));a.X="";b=b.substring(1+c|0)}}}We.prototype.$classData=x({Sb:0},"java.lang.JSConsoleBasedPrintStream",{Sb:1,Yd:1,Xd:1,Bb:1,b:1,zb:1,Jb:1,Ab:1,Ib:1});function Ye(){this.h=null}Ye.prototype=new y;
Ye.prototype.constructor=Ye;function Z(){}Z.prototype=Ye.prototype;Ye.prototype.f=function(){return this.h};Ye.prototype.o=function(){return xa(this)};function Ze(){}Ze.prototype=new y;Ze.prototype.constructor=Ze;function $e(){}$e.prototype=Ze.prototype;function af(){}af.prototype=new Ve;af.prototype.constructor=af;af.prototype.a=function(){M.prototype.a.call(this);bf=this;(new $d).a();return this};
af.prototype.$classData=x({Wc:0},"scala.collection.IndexedSeq$",{Wc:1,kd:1,va:1,ua:1,R:1,E:1,b:1,S:1,F:1});var bf=void 0;function ob(){bf||(bf=(new af).a());return bf}function cf(){this.K=this.Ba=0;this.ha=null}cf.prototype=new ve;cf.prototype.constructor=cf;cf.prototype.v=function(){this.K>=this.Ba&&pb().Aa.v();var a=this.ha.xa(this.K);this.K=1+this.K|0;return a};function df(a,b){var c=new cf;c.Ba=b;if(null===a)throw gd(id(),null);c.ha=a;c.K=0;return c}cf.prototype.A=function(){return this.K<this.Ba};
cf.prototype.$classData=x({Zc:0},"scala.collection.IndexedSeqLike$Elements",{Zc:1,Fa:1,b:1,Ga:1,Q:1,P:1,oe:1,d:1,c:1});function rd(){this.H=this.q=null}rd.prototype=new me;rd.prototype.constructor=rd;e=rd.prototype;e.ga=function(){return"JavaScriptException"};e.ea=function(){return 1};e.ma=function(){this.stackdata=this.H;return this};e.fa=function(a){switch(a){case 0:return this.H;default:throw(new U).i(""+a);}};e.Ta=function(){var a=this.H;return void 0===a?"undefined":a.toString()};
e.ba=function(a){this.H=a;L.prototype.y.call(this,null);return this};e.o=function(){return Gc(this)};e.qa=function(){return He(this)};e.$classData=x({Ia:0},"scala.scalajs.js.JavaScriptException",{Ia:1,N:1,L:1,z:1,b:1,c:1,Da:1,g:1,d:1});function lc(){this.h=null}lc.prototype=new Z;lc.prototype.constructor=lc;lc.prototype.a=function(){this.h="Boolean";return this};lc.prototype.$classData=x({xc:0},"scala.reflect.ManifestFactory$BooleanManifest$",{xc:1,B:1,b:1,n:1,m:1,l:1,j:1,d:1,c:1,g:1});var kc=void 0;
function Yb(){this.h=null}Yb.prototype=new Z;Yb.prototype.constructor=Yb;Yb.prototype.a=function(){this.h="Byte";return this};Yb.prototype.$classData=x({yc:0},"scala.reflect.ManifestFactory$ByteManifest$",{yc:1,B:1,b:1,n:1,m:1,l:1,j:1,d:1,c:1,g:1});var Xb=void 0;function bc(){this.h=null}bc.prototype=new Z;bc.prototype.constructor=bc;bc.prototype.a=function(){this.h="Char";return this};
bc.prototype.$classData=x({zc:0},"scala.reflect.ManifestFactory$CharManifest$",{zc:1,B:1,b:1,n:1,m:1,l:1,j:1,d:1,c:1,g:1});var ac=void 0;function jc(){this.h=null}jc.prototype=new Z;jc.prototype.constructor=jc;jc.prototype.a=function(){this.h="Double";return this};jc.prototype.$classData=x({Ac:0},"scala.reflect.ManifestFactory$DoubleManifest$",{Ac:1,B:1,b:1,n:1,m:1,l:1,j:1,d:1,c:1,g:1});var ic=void 0;function hc(){this.h=null}hc.prototype=new Z;hc.prototype.constructor=hc;
hc.prototype.a=function(){this.h="Float";return this};hc.prototype.$classData=x({Bc:0},"scala.reflect.ManifestFactory$FloatManifest$",{Bc:1,B:1,b:1,n:1,m:1,l:1,j:1,d:1,c:1,g:1});var gc=void 0;function dc(){this.h=null}dc.prototype=new Z;dc.prototype.constructor=dc;dc.prototype.a=function(){this.h="Int";return this};dc.prototype.$classData=x({Cc:0},"scala.reflect.ManifestFactory$IntManifest$",{Cc:1,B:1,b:1,n:1,m:1,l:1,j:1,d:1,c:1,g:1});var cc=void 0;function fc(){this.h=null}fc.prototype=new Z;
fc.prototype.constructor=fc;fc.prototype.a=function(){this.h="Long";return this};fc.prototype.$classData=x({Dc:0},"scala.reflect.ManifestFactory$LongManifest$",{Dc:1,B:1,b:1,n:1,m:1,l:1,j:1,d:1,c:1,g:1});var ec=void 0;function ef(){this.r=null}ef.prototype=new $e;ef.prototype.constructor=ef;function ff(){}ff.prototype=ef.prototype;ef.prototype.f=function(){return this.r};ef.prototype.o=function(){return xa(this)};function $b(){this.h=null}$b.prototype=new Z;$b.prototype.constructor=$b;
$b.prototype.a=function(){this.h="Short";return this};$b.prototype.$classData=x({Hc:0},"scala.reflect.ManifestFactory$ShortManifest$",{Hc:1,B:1,b:1,n:1,m:1,l:1,j:1,d:1,c:1,g:1});var Zb=void 0;function nc(){this.h=null}nc.prototype=new Z;nc.prototype.constructor=nc;nc.prototype.a=function(){this.h="Unit";return this};nc.prototype.$classData=x({Ic:0},"scala.reflect.ManifestFactory$UnitManifest$",{Ic:1,B:1,b:1,n:1,m:1,l:1,j:1,d:1,c:1,g:1});var mc=void 0;function A(){}A.prototype=new Re;
A.prototype.constructor=A;A.prototype.a=function(){M.prototype.a.call(this);qb=this;(new O).a();return this};A.prototype.$classData=x({nd:0},"scala.collection.immutable.List$",{nd:1,va:1,ua:1,R:1,E:1,b:1,S:1,F:1,d:1,c:1});var qb=void 0;function yb(){}yb.prototype=new Re;yb.prototype.constructor=yb;yb.prototype.a=function(){M.prototype.a.call(this);return this};yb.prototype.$classData=x({td:0},"scala.collection.immutable.Stream$",{td:1,va:1,ua:1,R:1,E:1,b:1,S:1,F:1,d:1,c:1});var xb=void 0;
function pc(){this.r=null}pc.prototype=new ff;pc.prototype.constructor=pc;pc.prototype.a=function(){this.r="Any";Oe();rb();r(Da);return this};pc.prototype.$classData=x({vc:0},"scala.reflect.ManifestFactory$AnyManifest$",{vc:1,sa:1,ra:1,b:1,n:1,m:1,l:1,j:1,d:1,c:1,g:1});var oc=void 0;function tc(){this.r=null}tc.prototype=new ff;tc.prototype.constructor=tc;tc.prototype.a=function(){this.r="AnyVal";Oe();rb();r(Da);return this};
tc.prototype.$classData=x({wc:0},"scala.reflect.ManifestFactory$AnyValManifest$",{wc:1,sa:1,ra:1,b:1,n:1,m:1,l:1,j:1,d:1,c:1,g:1});var sc=void 0;function vc(){this.r=null}vc.prototype=new ff;vc.prototype.constructor=vc;vc.prototype.a=function(){this.r="Nothing";Oe();rb();r(ie);return this};vc.prototype.$classData=x({Ec:0},"scala.reflect.ManifestFactory$NothingManifest$",{Ec:1,sa:1,ra:1,b:1,n:1,m:1,l:1,j:1,d:1,c:1,g:1});var uc=void 0;function xc(){this.r=null}xc.prototype=new ff;
xc.prototype.constructor=xc;xc.prototype.a=function(){this.r="Null";Oe();rb();r(jd);return this};xc.prototype.$classData=x({Fc:0},"scala.reflect.ManifestFactory$NullManifest$",{Fc:1,sa:1,ra:1,b:1,n:1,m:1,l:1,j:1,d:1,c:1,g:1});var wc=void 0;function rc(){this.r=null}rc.prototype=new ff;rc.prototype.constructor=rc;rc.prototype.a=function(){this.r="Object";Oe();rb();r(Da);return this};
rc.prototype.$classData=x({Gc:0},"scala.reflect.ManifestFactory$ObjectManifest$",{Gc:1,sa:1,ra:1,b:1,n:1,m:1,l:1,j:1,d:1,c:1,g:1});var qc=void 0;function Cb(){}Cb.prototype=new Ve;Cb.prototype.constructor=Cb;Cb.prototype.a=function(){M.prototype.a.call(this);Bb=this;return this};Cb.prototype.$classData=x({vd:0},"scala.collection.immutable.Vector$",{vd:1,kd:1,va:1,ua:1,R:1,E:1,b:1,S:1,F:1,d:1,c:1});var Bb=void 0;function gf(){}gf.prototype=new y;gf.prototype.constructor=gf;function hf(){}
hf.prototype=gf.prototype;gf.prototype.Oa=function(a,b,c,d){return Pc(this,a,b,c,d)};
gf.prototype.Ja=function(){var a;a:{a=ga(this).C.name;for(var b=-1+(a.length|0)|0;;)if(-1!==b&&36===(65535&(a.charCodeAt(b)|0)))b=-1+b|0;else break;if(-1===b||46===(65535&(a.charCodeAt(b)|0)))a="";else for(var c="";;){for(var d=1+b|0;;)if(-1!==b&&57>=(65535&(a.charCodeAt(b)|0))&&48<=(65535&(a.charCodeAt(b)|0)))b=-1+b|0;else break;for(var g=b;;)if(-1!==b&&36!==(65535&(a.charCodeAt(b)|0))&&46!==(65535&(a.charCodeAt(b)|0)))b=-1+b|0;else break;var l=1+b|0;if(b===g&&d!==(a.length|0)){a=c;break a}for(;;)if(-1!==
b&&36===(65535&(a.charCodeAt(b)|0)))b=-1+b|0;else break;var g=-1===b?!0:46===(65535&(a.charCodeAt(b)|0)),m;(m=g)||(m=65535&(a.charCodeAt(l)|0),m=!(90<m&&127>m||65>m));if(m){d=a.substring(l,d);l=c;if(null===l)throw(new pe).a();c=""===l?d:""+d+Id(46)+c;if(g){a=c;break a}}}}return a};function jf(a,b){for(var c=0,d=a.u();c<d;)b.x(a.xa(c)),c=1+c|0}function kf(){}kf.prototype=new hf;kf.prototype.constructor=kf;function lf(){}lf.prototype=kf.prototype;kf.prototype.I=function(a){for(var b=this.ca();b.A();)a.x(b.v())};
function mf(){}mf.prototype=new lf;mf.prototype.constructor=mf;function of(){}of.prototype=mf.prototype;mf.prototype.f=function(){var a=this.Ja()+"(";return Oc(this,a,", ")};function pf(){}pf.prototype=new of;pf.prototype.constructor=pf;function qf(){}qf.prototype=pf.prototype;function rf(){}rf.prototype=new of;rf.prototype.constructor=rf;function sf(){}e=sf.prototype=rf.prototype;e.x=function(a){throw(new U).i(""+(a|0));};e.I=function(){};e.ca=function(){var a=new Ie;a.Wd=this;return a};e.u=function(){return 0};
e.o=function(){return vd(this)};e.Ja=function(){return"List"};function tf(){}tf.prototype=new sf;tf.prototype.constructor=tf;e=tf.prototype;e.a=function(){return this};e.ga=function(){return"Nil"};e.ea=function(){return 0};e.fa=function(a){throw(new U).i(""+a);};e.qa=function(){return He(this)};
e.$classData=x({qd:0},"scala.collection.immutable.Nil$",{qd:1,md:1,cb:1,bb:1,db:1,b:1,pb:1,qb:1,ub:1,sb:1,Q:1,P:1,jb:1,mb:1,ib:1,tb:1,kb:1,eb:1,fb:1,lb:1,g:1,nb:1,ab:1,G:1,gb:1,hb:1,ob:1,Ce:1,De:1,Be:1,Fe:1,be:1,pe:1,qe:1,Da:1,re:1,d:1,c:1});var uf=void 0;function rb(){uf||(uf=(new tf).a())}function vf(){}vf.prototype=new qf;vf.prototype.constructor=vf;function xf(){}xf.prototype=vf.prototype;function J(){this.w=null}J.prototype=new qf;J.prototype.constructor=J;e=J.prototype;
e.a=function(){J.prototype.Eb.call(this,16,"");return this};e.xa=function(a){a=65535&(this.w.e.charCodeAt(a)|0);return Id(a)};e.x=function(a){a=65535&(this.w.e.charCodeAt(a|0)|0);return Id(a)};e.wb=function(a,b){return this.w.e.substring(a,b)};e.f=function(){return this.w.e};e.I=function(a){jf(this,a)};e.ca=function(){return df(this,this.w.u())};function Rc(a,b){a=a.w;a.e=""+a.e+b}e.Eb=function(a,b){a=(new S).$((b.length|0)+a|0);a.e=""+a.e+b;J.prototype.Hb.call(this,a);return this};e.u=function(){return this.w.u()};
e.Hb=function(a){this.w=a;return this};function Sc(a,b){var c=a.w;c.e+=""+b;return a}e.o=function(){return vd(this)};e.$classData=x({Ed:0},"scala.collection.mutable.StringBuilder",{Ed:1,wd:1,cb:1,bb:1,db:1,b:1,pb:1,qb:1,ub:1,sb:1,Q:1,P:1,jb:1,mb:1,ib:1,tb:1,kb:1,eb:1,fb:1,lb:1,g:1,nb:1,ab:1,G:1,gb:1,hb:1,ob:1,Cd:1,Bd:1,Gd:1,cc:1,Dd:1,yd:1,ac:1,Xa:1,Wa:1,zd:1,Vc:1,Yc:1,Ad:1,Ee:1,$c:1,ke:1,t:1,Le:1,xd:1,jd:1,gd:1,d:1,c:1});function Y(){this.T=null}Y.prototype=new xf;Y.prototype.constructor=Y;e=Y.prototype;
e.xa=function(a){return this.T[a]};e.x=function(a){return this.T[a|0]};e.I=function(a){jf(this,a)};e.ca=function(){return df(this,this.T.length|0)};e.u=function(){return this.T.length|0};e.o=function(){return vd(this)};function X(a,b){a.T=b;return a}e.Ja=function(){return"WrappedArray"};
e.$classData=x({Hd:0},"scala.scalajs.js.WrappedArray",{Hd:1,Ge:1,wd:1,cb:1,bb:1,db:1,b:1,pb:1,qb:1,ub:1,sb:1,Q:1,P:1,jb:1,mb:1,ib:1,tb:1,kb:1,eb:1,fb:1,lb:1,g:1,nb:1,ab:1,G:1,gb:1,hb:1,ob:1,Cd:1,Bd:1,Gd:1,cc:1,Dd:1,yd:1,ac:1,Xa:1,Ie:1,Je:1,jd:1,gd:1,ze:1,se:1,Ae:1,zd:1,Vc:1,Yc:1,Ad:1,He:1,Ke:1,$c:1,xd:1});Wa||(Wa=(new Va).a());var yf=Wa,zf;zf=new (Fa(ha).za)([]);
(function(a){var b=Qa(),c=Oa.resolve(),c=cd(t(),c)?c:c+"/app",d=Qa["static"](c+"/public");b.use("/public",d);d=Pa.json();b.use(d);d=new (Hd())(!1);d=Pa.urlencoded(d);b.use(d);b.get("/",function(a,b){return function(a,c){c.sendFile(b+"/views/index.html")}}(a,c)).get("/scores/:name",function(){return function(a,b){var c=Ee(Ge(new W,X(new Y,["Got request "," with origUrl\x3d"," and "])),X(new Y,[a,a.originalUrl])),d=Ge(new W,X(new Y,["name\x3d",""])),v=a.params;if(!Zc().Ea.call(v,"name"))throw(new V).i("key not found: name");
c=""+c+Ee(d,X(new Y,[v.name]));Xe(Nd().Ca.wa,c+"\n");c=a.originalUrl;a=8+(a.originalUrl.indexOf("/scores/")|0)|0;a=c.substring(a);b.send(a)}}(a)).post("/scores/:name",function(){return function(a){a.ip;a=a.params;if(!Zc().Ea.call(a,"name"))throw(new V).i("key not found: name");}}(a)).listen(3E3,function(a,b,c){return function(){var a=Ee(Ge(new W,X(new Y,["Server listening on port "," in dir ",""])),X(new Y,[b,c]));Xe(Nd().Ca.wa,a+"\n")}}(a,3E3,c))})(yf,zf);
//# sourceMappingURL=backend-opt.js.map
